<?php
/**
 * @file
 * Code for the Ting covers backside feature.
 */

include_once 'ting_covers_backside.features.inc';

/**
 * Implements hook_menu().
 */
function ting_covers_backside_menu() {
  $items = array();

  $items['ting/covers/backside'] = array(
    'title' => 'Retreives backside cover for Ting objects',
    'page callback' => 'ting_covers_backside_objects',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'drupal_json_output',
  );
  $items['admin/config/ting/covers/backside'] = array(
    'title' => 'Backside',
    'description' => 'Configure how covers backside are handled.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_covers_backside_admin_settings_form'),
    'access arguments' => array('administer ting settings'),
    'file' => 'ting_covers_backside.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function ting_covers_backside_theme($existing, $type, $theme, $path) {
  return array(
    'ting_object_backside' => array(
      'template' => 'templates/ting-covers-backside',
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_cron().
 */
function ting_covers_backside_cron() {
  _ting_covers_backside_delete_old_files(REQUEST_TIME - variable_get('ting_covers_cache_lifetime', TING_COVERS_DEFAULT_CACHE_LIFETIME));
}

/**
 * Delete ting backside cover files.
 *
 * @param int $time
 *   Timestamp where older files will be deleted. Omit or set to NULL to delete
 *   all files.
 */
function _ting_covers_backside_delete_old_files($time = NULL) {
  // Collect potential locations of cover folders.
  $files_dir = file_default_scheme() . '://';
  $image_dirs = array($files_dir);

  $styles_dir = $files_dir . 'styles';
  foreach (scandir($styles_dir) as $style_dir) {
    $style_dir = $styles_dir . DIRECTORY_SEPARATOR . $style_dir . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR;
    if (is_dir($style_dir)) {
      $image_dirs[] = $style_dir;
    }
  }

  // Collect backside cover files.
  $backover_files = array();
  foreach ($image_dirs as $uri) {
    $ting_backcovers_dir = $uri . 'ting' . DIRECTORY_SEPARATOR . 'backcovers';
    if (is_dir($ting_backcovers_dir)) {
      $backover_files = array_merge($backover_files, file_scan_directory($ting_backcovers_dir, "/./"));
    }
  }

  // Delete obsolete files.
  foreach ($backover_files as $file) {
    if (!$time || (filemtime($file->uri) < $time)) {
      file_unmanaged_delete($file->uri);
      // Delete image cache derivatives.
      image_path_flush($file->uri);
    }
  }
}

/**
 * Menu callback to get backside cover information.
 */
function ting_covers_backside_objects() {
  $ids = array();
  foreach ($_POST['coverData'] as $cover_info) {
    $ids[] = $cover_info['id'];
  }
  $backside_covers = ting_covers_backside_get($ids);

  $covers = array();
  foreach ($ids as $id) {
    // Load front page cover.
    $path = ting_covers_object_path($id);
    $front_cover = FALSE;
    if (file_exists($path)) {
      $front_cover = image_style_url('ting_cover_large', $path);
    }

    // Load backside cover.
    $backside_cover = FALSE;
    if (in_array($id, array_keys($backside_covers)) && file_exists($backside_covers[$id])) {
      $backside_cover = file_create_url($backside_covers[$id]);
    }
    if ($front_cover || $backside_cover) {
      $covers[$id] = theme(
        'ting_object_backside',
        array(
          'entity_id' => $id,
          'hash' => md5($id),
          'front_cover' => $front_cover,
          'backside_cover' => $backside_cover,
        )
      );
    }
  }

  return $covers;
}

/**
 * Get backside covers for an array of ids.
 *
 * @param array $requested_backside_covers
 *   Ids of entities to return covers for.
 *
 * @return array
 *   Array of id => file path for found covers.
 */
function ting_covers_backside_get(array $requested_backside_covers) {
  $entities = array();
  $backside_covers = array();

  // Create array of loaded entities for passing to hooks.
  foreach ($requested_backside_covers as $id) {
    // Ensure that the id at least seems valid.
    if (!mb_check_encoding($id, "UTF-8")) {
      continue;
    }

    // Determine if the local id is a known negative.
    if (cache_get('ting_backside_covers:' . $id)) {
      continue;
    }

    // If we already have a valid cover image, use it.
    $path = ting_covers_backside_object_path($id);
    if (file_exists($path)) {
      $backside_covers[$id] = $path;
      continue;
    }

    // Queue for fetching by hook.
    $entities[$id] = ding_entity_load($id);
  }

  $bc = array();

  // Exceptions should only be thrown if something is so wrong,
  // that no backside files can be fetched.
  try {
    $service = new AdditionalInformationBacksideService(variable_get('ting_covers_addi_wsdl_url', ''), variable_get('ting_covers_addi_username', ''), variable_get('ting_covers_addi_group', ''), variable_get('ting_covers_addi_password', ''));

    // We're working by localId, so create a look-up table.
    $id_map = array();
    foreach ($entities as $id => $entity) {
      $id_map[$entity->localId] = $id;
    }

    // Local ids = Faust numbers. Library object identifiers can be confusing.
    $retrieved = $service->getByFaustNumber(array_keys($id_map));

    foreach ($retrieved as $local_id => $backside_cover) {
      // Try to extract the image url from the result.
      if ($backside_cover->backsideUri) {
        $source_url = $backside_cover->backsideUri;
        // Return the path to the backside_cover.
        $bc[$id_map[$local_id]] = $source_url;
      }
    }
  }
  catch (Exception $e) {
    watchdog('ting_covers_backside', 'Unable to retrieve covers from ADDI: %message', array('%message' => $e->getMessage()), WATCHDOG_ERROR);

    // Error in fetching, return no covers.
    return array();
  }

  // Fetch covers by calling hook.
  foreach ($bc as $id => $uri) {
    if ($uri && $path = _ting_covers_backside_get_file($id, $uri)) {
      $backside_covers[$id] = $path;
    }
    // Remove elements where a cover has been found, or suppressed.
    unset($entities[$id]);
  }

  // Mark all remaining as not found in cache.
  foreach ($entities as $id => $entity) {
    cache_set('ting_backside_covers:' . $id, 1, 'cache', $_SERVER['REQUEST_TIME'] + TING_COVERS_DEFAULT_CACHE_LIFETIME);
  }

  return $backside_covers;
}

/**
 * Moves/downloads an URI into the cover cache.
 *
 * @param string $id
 *   Ting entity id.
 * @param string $uri
 *   URI of file or local path.
 */
function _ting_covers_backside_get_file($id, $uri) {
  if (!($url = parse_url($uri))) {
    // Seriously malformed, ignore it.
    return FALSE;
  }

  // Flat paths don't get a scheme.
  if (!isset($url['scheme']) && file_exists($uri)) {
    $url['scheme'] = 'file';
  }

  $path = ting_covers_backside_object_path($id);

  switch ($url['scheme']) {
    case 'http':
    case 'https':
      if (ting_covers_backside_fetch_backover($path, $uri)) {
        return $path;
      }
      break;

    case 'private':
    case 'file':
      if (file_unmanaged_save_data($uri, $path, FILE_EXISTS_REPLACE)) {
        return $path;
      }
  }

  return FALSE;
}

/**
 * Helper function to fetch and save a backside cover image file.
 *
 * Cover fetching modules should use this if fetching the cover is a simple GET
 * request.
 *
 * @param string $filename
 *   File name, including its path within Drupal's file folder.
 * @param string $image_url
 *   URL for the source image file.
 *
 * @return mixed
 *   A file object or FALSE on error.
 *
 * @see image_style_create_derivative()
 */
function ting_covers_backside_fetch_backover($filename, $image_url) {
  $result = drupal_http_request($image_url);

  // Bail if the HTTP request failed.
  if ($result->code != 200) {
    return FALSE;
  }

  // Get the folder for the final location of this preset.
  $directory = dirname($filename);

  // Build the destination folder tree if it doesn't already exist.
  if (!file_prepare_directory($directory, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
    watchdog('ting_covers', 'Failed to create directory: %directory', array('%directory' => $directory), WATCHDOG_ERROR);
    return FALSE;
  }

  $file = file_unmanaged_save_data($result->data, $filename, FILE_EXISTS_REPLACE);

  if ($file) {
    return $file;
  }

  return FALSE;
}

/**
 * Return the path to the backside cover of the object.
 *
 * The filename is the ID base64 encoded, so we can reverse it later.
 */
function ting_covers_backside_object_path($object_id) {
  return file_default_scheme() . '://ting' . DIRECTORY_SEPARATOR . 'backcovers' . DIRECTORY_SEPARATOR . preg_replace('/[^a-z0-9]/', '-', $object_id) . '.pdf';
}

/**
 * Implements hook_preprocess_HOOK.
 *
 * Attach modal window wrapper to be replaced with the covers.
 *
 * @param $variables
 */
function ting_covers_backside_preprocess_field(&$variables) {
  if ($variables['element']['#field_type'] == 'ting_cover') {
    $image_style = $variables['element']['#view_mode'] . ':' . $variables['items'][0]['#image_style'];
    $display_modal = in_array($image_style, array_filter(variable_get('ting_backside_covers_modes', array())));

    if ($display_modal) {
      $module_path = drupal_get_path('module', 'ting_covers_backside');
      $variables['items'][0]['#attached']['js'][] = $module_path . '/js/ting_covers_backside.js';
      $variables['items'][0]['#attached']['js'][] = $module_path . '/js/jquery.reveal.js';
      $variables['items'][0]['#attached']['css'][] = $module_path . '/css/reveal.css';
      $variables['items'][0]['#suffix'] = '<div class="backside-covers-wrapper"></div>';
    }
  }
}
